import { ingestDocument } from "../../services/documentIntelligence";
import {
  findUploadByFilename,
  getGeneratedImage,
  getImageBuffer,
  getSessionImages,
  getSessionUploads,
  setGeneratedImage,
  type SessionUpload
} from "../../services/uploadSession";
import {
  generateFromPrompt,
  generateFromReferenceImage,
  getLastGeminiImageError,
  isNanoBananaConfigured,
  type NanoBananaResult
} from "../../services/nanoBanana";
import { toolLog } from "../../utils/requestLog";
import { searchTranscriptsByMessage } from "../../db/transcriptQueries";
import type { IntentResponse } from "./types";

const GENERATION_INTENT =
  /\b(generate|create|finish(?:ed)?|make this look(?: like)?(?: done)?|what would this look like finished|render|visualize|show me finished|complete this lawn|complete the lawn|transform|make it look)\b/i;

const STORE_INTENT =
  /\b(store it|save it|keep it|add to documents|file it|store that|save that)\b/i;

const SEND_INTENT = /\b(send it|email it|text it|forward it)\b/i;

const ANALYZE_INTENT = /\b(analyze it|read it|summarize it|what does it say|look at it|review it)\b/i;

const TRANSCRIPT_QUERY =
  /\b(what did we decide|what was decided|meeting notes|job site recording|recording from|transcript from|what did we discuss)\b/i;

const WHICH_IMAGE = /\b(first|second|1|2|one|two|left|right)\b/i;

function emptyUi(): IntentResponse["ui"] {
  return { panel: null, data: [], action: null };
}

function geminiNotConfiguredResponse(): IntentResponse {
  return {
    speech: "Image generation needs GEMINI_API_KEY on the server sir.",
    intent: "image.generate.unconfigured",
    entities: {},
    ui: emptyUi(),
    tool: { name: null, args: {} }
  };
}

function geminiFailedResponse(detail?: string | null): IntentResponse {
  const raw = detail?.trim() || getLastGeminiImageError();
  const speech = raw
    ? `Render failed sir — ${raw.replace(/\s+/g, " ").slice(0, 160)}`
    : "Couldn't render that one sir — try a JPG or PNG reference, or simplify the prompt.";
  return {
    speech,
    intent: "image.generate.failed",
    entities: {},
    ui: emptyUi(),
    tool: { name: null, args: {} }
  };
}

export function buildGeneratedImageUi(
  generated: NanoBananaResult,
  label = "Generated by JARVIS"
): IntentResponse["ui"] {
  return {
    panel: "photo",
    action: "show",
    data: [
      {
        type: "generated_image",
        base64: generated.imageBase64,
        mimeType: generated.mimeType,
        label,
        imageBase64: generated.imageBase64,
        mime_type: generated.mimeType,
        caption: label
      }
    ]
  };
}

export function isImageGenerationIntent(message: string): boolean {
  return GENERATION_INTENT.test(message);
}

export async function tryTranscriptQueryRoute(message: string): Promise<IntentResponse | null> {
  if (!TRANSCRIPT_QUERY.test(message)) return null;

  const rows = searchTranscriptsByMessage(message, 3);
  if (!rows.length) {
    return {
      speech: "I don't have a recording for that day yet, sir.",
      intent: "transcript.query",
      entities: {},
      ui: emptyUi(),
      tool: { name: null, args: {} }
    };
  }

  const top = rows[0];
  const speechParts = [top.summary || "Recording found."];
  if (top.actionItems) speechParts.push(`Action items: ${top.actionItems.slice(0, 200)}.`);

  return {
    speech: speechParts.join(" "),
    intent: "transcript.query",
    entities: { transcriptId: top.id },
    ui: emptyUi(),
    tool: { name: null, args: {} }
  };
}

/** Core Gemini image generation — used by chat routes and executeTool. */
export async function runImageGeneration(
  message: string,
  sessionId: string,
  target: { uploadId: string; mimeType: string; filename: string } | null
): Promise<IntentResponse> {
  toolLog(
    `image.generate start session=${sessionId.slice(0, 12)} hasTarget=${Boolean(target)} promptLen=${message.length}`
  );

  if (!isNanoBananaConfigured()) {
    return geminiNotConfiguredResponse();
  }

  let generated: NanoBananaResult | null = null;

  if (target) {
    toolLog(`image.generate target uploadId=${target.uploadId} file=${target.filename}`);
    const buffer = getImageBuffer(target.uploadId);
    if (!buffer) {
      return {
        speech: `I can't find that image in session anymore sir (${target.filename}). Upload it again.`,
        intent: "image.generate.missing",
        entities: {},
        ui: emptyUi(),
        tool: { name: null, args: {} }
      };
    }

    toolLog(`image.generate calling Gemini with reference bytes=${buffer.length}`);
    generated = await generateFromReferenceImage({
      imageBuffer: buffer,
      mimeType: target.mimeType,
      referenceImageBase64: buffer.toString("base64"),
      referenceImageMimeType: target.mimeType,
      prompt: message
    });
  } else {
    toolLog("image.generate calling Gemini text-only");
    generated = await generateFromPrompt(message);
  }

  if (!generated) {
    return geminiFailedResponse(getLastGeminiImageError());
  }

  if (target) {
    setGeneratedImage(sessionId, {
      imageBase64: generated.imageBase64,
      mimeType: generated.mimeType,
      sourceUploadId: target.uploadId,
      sourceFilename: target.filename,
      generatedAt: Date.now()
    });
  }

  return {
    speech: "Done sir. Your finished landscaping render.",
    intent: "image.generate",
    entities: target ? { sourceFilename: target.filename } : { textOnly: true },
    ui: buildGeneratedImageUi(generated),
    tool: { name: null, args: {} }
  };
}

export async function tryImageGenerationRoute(
  message: string,
  sessionId: string
): Promise<IntentResponse | null> {
  if (!isImageGenerationIntent(message)) return null;

  const images = getSessionImages(sessionId);

  if (images.length > 1 && !findUploadByFilename(sessionId, message.replace(WHICH_IMAGE, "").trim())) {
    const names = images.map((i) => i.filename).join(" or ");
    return {
      speech: `Which image sir — ${names}?`,
      intent: "image.generate.select",
      entities: { options: images.map((i) => i.filename) },
      ui: emptyUi(),
      tool: { name: null, args: {} }
    };
  }

  let target: { uploadId: string; mimeType: string; filename: string } | null = null;

  if (images.length) {
    let pick = images[0];
    if (images.length > 1) {
      const hinted = findUploadByFilename(sessionId, message);
      if (hinted) pick = hinted;
      else if (/\b(second|2|two|right)\b/i.test(message) && images[1]) pick = images[1];
    }
    target = {
      uploadId: pick.uploadId,
      mimeType: pick.mimeType,
      filename: pick.filename
    };
  }

  return runImageGeneration(message, sessionId, target);
}

function logSessionImagesForResolve(sessionId: string, images: SessionUpload[]) {
  const uploads = getSessionUploads(sessionId);
  const snapshot = images.map((i) => ({
    uploadId: i.uploadId.slice(0, 8),
    filename: i.filename,
    isImage: i.isImage,
    hasBuffer: Boolean(getImageBuffer(i.uploadId))
  }));
  toolLog(
    `resolveImageGenerationTarget session=${sessionId.slice(0, 12)} getSessionImages=${JSON.stringify(snapshot)} sessionUploads=${uploads.length} bufferedKeys=${uploads.filter((u) => getImageBuffer(u.uploadId)).length}`
  );
}

function toImageTarget(hit: SessionUpload) {
  return { uploadId: hit.uploadId, mimeType: hit.mimeType, filename: hit.filename };
}

/** Resolve session image target for tool path (optional uploadId / filename in args). */
export function resolveImageGenerationTarget(
  sessionId: string,
  message: string,
  args: Record<string, unknown> = {},
  userMessage?: string
): { uploadId: string; mimeType: string; filename: string } | null {
  const images = getSessionImages(sessionId);
  logSessionImagesForResolve(sessionId, images);
  if (!images.length) return null;

  const disambigText = (userMessage || message).replace(WHICH_IMAGE, "").trim();

  const uploadIdHint = String(args.uploadId || args.upload_id || "").trim();
  if (uploadIdHint) {
    const hit = images.find((i) => i.uploadId === uploadIdHint);
    if (hit) return toImageTarget(hit);
  }

  const documentIdHint = String(args.documentId || args.document_id || "").trim();
  if (documentIdHint) {
    const hit = images.find((i) => i.documentId === documentIdHint);
    if (hit) return toImageTarget(hit);
  }

  const filenameHint = String(args.filename || args.sourceFilename || "").trim();
  if (filenameHint) {
    const hit = findUploadByFilename(sessionId, filenameHint);
    if (hit && (hit.isImage || getImageBuffer(hit.uploadId))) {
      return toImageTarget(hit);
    }
  }

  if (images.length > 1 && !findUploadByFilename(sessionId, disambigText)) {
    const bufferedOnly = images.filter((i) => getImageBuffer(i.uploadId));
    if (bufferedOnly.length === 1) {
      return toImageTarget(bufferedOnly[0]);
    }
    return null;
  }

  let pick = images[images.length - 1];
  if (images.length > 1) {
    const hinted = findUploadByFilename(sessionId, disambigText || message);
    if (hinted) pick = hinted;
    else if (/\b(second|2|two|right)\b/i.test(disambigText || message) && images[1]) {
      pick = images[1];
    }
  }

  return toImageTarget(pick);
}

export async function tryUploadFollowUpRoute(
  message: string,
  sessionId: string
): Promise<IntentResponse | null> {
  if (SEND_INTENT.test(message) && getGeneratedImage(sessionId)) {
    return {
      speech:
        "Generated image is in your photo panel sir — use the download button to save it.",
      intent: "image.send.unavailable",
      entities: {},
      ui: emptyUi(),
      tool: { name: null, args: {} }
    };
  }

  if (STORE_INTENT.test(message)) {
    const generated = getGeneratedImage(sessionId);
    if (generated) {
      const stamp = new Date().toISOString().slice(0, 10);
      const title = `Generated ${stamp} — ${generated.sourceFilename}`;
      const buffer = Buffer.from(generated.imageBase64, "base64");
      await ingestDocument({
        buffer,
        title,
        mimeType: generated.mimeType,
        originalFilename: `${title}.png`,
        source: "upload"
      });
      return {
        speech: `Stored sir. Saved as ${title}.`,
        intent: "image.store",
        entities: { title },
        ui: emptyUi(),
        tool: { name: null, args: {} }
      };
    }
  }

  const uploads = getSessionUploads(sessionId);
  if (!uploads.length) return null;

  if (isImageGenerationIntent(message) && getSessionImages(sessionId).length) {
    return tryImageGenerationRoute(message, sessionId);
  }

  if (ANALYZE_INTENT.test(message)) {
    const names = uploads.map((u) => u.filename).join(", ");
    return {
      speech: `I have ${uploads.length} file${uploads.length === 1 ? "" : "s"} ready — ${names}. Tell me what to extract or ask a specific question about the content, sir.`,
      intent: "upload.analyze",
      entities: { filenames: uploads.map((u) => u.filename) },
      ui: emptyUi(),
      tool: { name: null, args: {} }
    };
  }

  if (STORE_INTENT.test(message) && uploads.length) {
    return {
      speech: `Already in your knowledge base sir — ${uploads.map((u) => u.filename).join(", ")}.`,
      intent: "upload.already_stored",
      entities: {},
      ui: emptyUi(),
      tool: { name: null, args: {} }
    };
  }

  return null;
}
